### ISSUE TITLE
Creates links to speaker pages, but pages don't exist

### ISSUE THREAD

**Issue by nwautier** [TheCraigHewitt/Seriously-Simple-Speakers#3]
I'd assume that a speaker page would display their description and links to the episodes they are on, but that is not the case currently.

If you want to check my setup it is http://www.technopoly411.com

**Comment by jonathanbossenger** [comment]
@nwautier Speakers are a custom taxonomy so WordPress should load the default taxonomy archive template, which shows a list of all podcasts for that speaker.

I tested this out on my development environment and I was able to fix it by updating my permalinks ( Settings->Permalinks and then just hit 'Save changes'

Please try this and let me know if it works

**Comment by nwautier** [comment]
This did work.  Thank you!
